export const VideoDB = [
    {
      v_id: "x5ghoVBrx8o",
      category: "Gardening Basics",
      avatar: "http://i3.ytimg.com/vi/x5ghoVBrx8o/maxresdefault.jpg",
      title:"Summer Garden| What I am growing and How I am growing in my Balcony",
      views:224211,
      likes:7000,
      dislikes:100,
      channel: "Garden Up",
      postedOn: "Apr 28, 2021",
      subscriber: "1.2M",
      duration: "7:21",
      description:"Here is a short video on how i am doing gardening in my balcony in the summer. In this video it is shown what i am growing and how to grow a particular plant in the balcony....stay tuned for more."
    },
    {
        v_id: "oOJSCK9FPew",
        category: "Gardening Basics",
        avatar: "http://i3.ytimg.com/vi/oOJSCK9FPew/maxresdefault.jpg",
        title:"Solving the biggest problem: Watering Plants on a Vacation",
        views:449227,
        likes:9200,
        dislikes:200,
        channel: "Garden Up",
        postedOn: "Dec 4, 2021",
        subscriber: "1.2M",
        duration: "5:41",
        description:"Finding a huge space in big cities such as Mumbai is very difficult and very expensive. One way to deal with the challenges of a small house is by playing with the colour and a suitable choice of furniture. Here I introduce you to our tiny City house, where I live with my husband and my many many plants."
    },
    {
        v_id: "hedTA1L2_o4",
        category: "Gardening Basics",
        avatar: "http://i3.ytimg.com/vi/hedTA1L2_o4/maxresdefault.jpg",
        title:"The CORRECT way of REPOTTING Plants | Garden Up Shorts",
        views:118981,
        likes:5700,
        dislikes:65,
        channel: "Garden Up",
        postedOn: "Feb 11, 2021",
        subscriber: "1.2M",
        duration: "2:20",
        description:"If you have recently bought a plant from a nursery or an over grown plant that needs repotting, here is how you can easily repot a plant without killing it."
      },
      {
        v_id: "2rK0MnWbXbM",
        category: "Gardening Basics",
        avatar: "http://i3.ytimg.com/vi/2rK0MnWbXbM/maxresdefault.jpg",
        title:"Plant guide for shopping flowers this season",
        views:213375,
        likes:7300,
        dislikes:160,
        channel: "Garden Up",
        postedOn: "Jan 29, 2021",
        subscriber: "1.2M",
        duration: "7:47",
        description:"My advise for this season, grow lots of flowers. The temperature right now (Febraury-March) from Delhi to Kolkata to Bangalore to Mumbai is just perfect For beginners, I recommend Bougainvillea, Cactus crown and moss rose. Like wise for different seasons and different gardener levels I have recommendations for every one in this video."
      },
      {
        v_id: "UZKh_21-xyY",
        category: "Gardening Basics",
        avatar: "http://i3.ytimg.com/vi/UZKh_21-xyY/maxresdefault.jpg",
        title:"How and Why You should use Moss Stick for Indoor Plants",
        views:350327,
        likes:8500,
        dislikes:200,
        channel: "Garden Up",
        postedOn: "Feb 28, 2021",
        subscriber: "1.2M",
        duration: "5:29",
        description:"Adding a moss stick to your plant can help improve the growth of your. Here in this video I explain what moss sticks to use, what are its alternatives and how to use it especially for money plant, philodendron and monsteras."
      },
      {
        v_id: "SrOe-r07EwM",
        category: "Gardening Basics",
        avatar: "http://i3.ytimg.com/vi/SrOe-r07EwM/maxresdefault.jpg",
        title:"I have mastered the art of growing Rubber plant perfectly, I think.",
        views:805765,
        likes:16000,
        dislikes:400,
        channel: "Garden Up",
        postedOn: "Jan 31, 2020",
        subscriber: "1.2M",
        duration: "8:27",
        description:"Rubber Plant or Ficus Elastica is an easy and a beautiful indoor plant. It is easy to grow, both in India and US like indoor conditions. Here is how you can care for rubber plant or ficus elastica as an indoor plant in easy steps."
      },
      {
        v_id: "a-5lr12FrW4",
        category: "Gardening Basics",
        avatar: "http://i3.ytimg.com/vi/a-5lr12FrW4/maxresdefault.jpg",
        title:"Vegetables You can Grow in Pots in a Flat| Success and failures",
        views:884242,
        likes:16000,
        dislikes:500,
        channel: "Garden Up",
        postedOn: "Sep 26, 2019",
        subscriber: "1.2M",
        duration: "6:41",
        description:"Here are what greens i am going for home in our small balcony in Mumbai. In smaller spaces the challenge is what veggies you need to grow that dont need a lot of place. In this video I share ideas and suggestions for what vegetables and herbs are easy to grow in a balcony."
      },
      {
        v_id: "MB9U4QhrDFE",
        category: "DIY",
        avatar: "http://i3.ytimg.com/vi/MB9U4QhrDFE/maxresdefault.jpg",
        title:"How to grow plant in coffee mugs/Cups || Backyard Gardening",
        views:1131773,
        likes:11000,
        dislikes:700,
        channel: "Backyard Gardening",
        postedOn: "Dec 26, 2018",
        subscriber: "115K",
        duration: "6:58",
        description:"A short video of DIY in growing plant in coffee mugs which are not of use anymore."
      },
      {
        v_id: "kAny8gvVwMY",
        category: "DIY",
        avatar: "http://i3.ytimg.com/vi/uO3FuHw2zd0/maxresdefault.jpg",
        title:"DIY- Make Beautiful clay Pot using old waste cloth/DIY Clay planter",
        views:17116,
        likes:180,
        dislikes:17,
        channel: "Backyard Gardening",
        postedOn: "Mar 27, 2018",
        subscriber: "115k",
        duration: "6:09",
        description:"Learn the easiest way to make beautiful pot from old unused cloth."
      },
      {
        v_id: "bN34Y49fIXc",
        category: "DIY",
        avatar: "http://i3.ytimg.com/vi/JpEbjmOuD8w/maxresdefault.jpg",
        title:"DIY easy craft/DIY pebble mountain and waterfall craft with hot glue",
        views:5107,
        likes:70,
        dislikes:3,
        channel: "Backyard Gardening",
        postedOn: "Mar 24, 2018",
        subscriber: "115K",
        duration: "3:43",
        description:"Let's make a simple DIY with pebbles and hot glue."
      },
      {
        v_id: "czBC_F-elaI",
        category: "DIY",
        avatar: "http://i3.ytimg.com/vi/DXtZpc_aHkA/maxresdefault.jpg",
        title:"DIY: BEAUTIFUL VASE FROM WASTE BOTTLE",
        views:6234,
        likes:99,
        dislikes:11,
        channel: "Backyard Gardening",
        postedOn: "Mar 11, 2018",
        subscriber: "115K",
        duration: "2:50",
        description:"In today's video we will make beautiful vase out of waste bottle."
      },
      {
        v_id: "QEjJgNbnDL0",
        category: "DIY",
        avatar: "http://i3.ytimg.com/vi/tZGBr56KFC0/maxresdefault.jpg",
        title:"DIY stone Planter",
        views:1747,
        likes:28,
        dislikes:3,
        channel: "Backyard Gardening",
        postedOn: "Jul 10, 2018",
        subscriber: "115K",
        duration: "2:50",
        description:"A beautiful stone planter made using stone and hot glue."
      },
      {
        v_id: "N1UBt-tgbG0",
        category: "DIY",
        avatar: "http://i3.ytimg.com/vi/eoR1mUz5Qpk/maxresdefault.jpg",
        title:"DIY Coconut Shell planter/Grow plants in coconut shell",
        views:12438,
        likes:181,
        dislikes:7,
        channel: "Backyard Gardening",
        postedOn: "Jul 8, 2018",
        subscriber: "115K",
        duration: "4:42",
        description:"The best use of old used coconut shell to make planter of different colours."
      },
      {
        v_id: "Lgiu_JbLwuA",
        category: "Tips for Effective Gardening",
        avatar: "http://i3.ytimg.com/vi/2cJnGQYh7P4/maxresdefault.jpg",
        title:"How to use Neem oil as an organic insecticide/pesticide for all type of plants and flowers!!!",
        views:5857,
        likes:46,
        dislikes:2,
        channel: "Backyard Gardening",
        postedOn: "Aug 15, 2017",
        subscriber: "115K",
        duration: "1:53",
        description:"Learn the easiest way to get rid of all kind of insecticides like aphids, white flies and ants from all kind of plants and flowers."
      },
      {
        v_id: "Gl9XDkdMJMs",
        category: "Tips for Effective Gardening",
        avatar: "http://i3.ytimg.com/vi/1YrBZWDXUpY/maxresdefault.jpg",
        title:"How to Collect Carrot seeds from the carrot plant grown through carrot tops.",
        views:52200,
        likes:630,
        dislikes:20,
        channel: "Backyard Gardening",
        postedOn: "Jul 2, 2017",
        subscriber: "115K",
        duration: "1:30",
        description:"Learn how to collect carrot seeds from the carrot plant grown through the carrot tops. and grow your own organic carrots out of it."
      },
      {
        v_id: "8lt1nkBRYGc",
        category: "Tips for Effective Gardening",
        avatar: "http://i3.ytimg.com/vi/9bbQF_M48kY/maxresdefault.jpg",
        title:"Soil Preparation for kitchen garden",
        views:1914,
        likes:47,
        dislikes:2,
        channel: "Backyard Gardening",
        postedOn: "Apr 22, 2017",
        subscriber: "115K",
        duration: "3:12",
        description:"For a healthy garden, soil preparation is key to success. All vegetable & flower plants need soil which is rich in nutrients. We will talk about the preparation of soil before planting seeds, plants etc."
      },
      {
        v_id: "tO4cU_1NWFU",
        category: "Tips for Effective Gardening",
        avatar: "http://i3.ytimg.com/vi/UylRiYdo7Ws/maxresdefault.jpg",
        title:"Add this in your plants and see the magic",
        views:3819,
        likes:109,
        dislikes:1,
        channel: "Backyard Gardening",
        postedOn: "Mar 24, 2018",
        subscriber: "115K",
        duration: "1:57",
        description:"Today i will talk about magical uses of baking soda on plants and for your garden."
      },
      {
        v_id: "2or7tGTyswA",
        category: "Tips for Effective Gardening",
        avatar: "http://i3.ytimg.com/vi/pmHnW6ewjqU/maxresdefault.jpg",
        title:"Top 5 mosquito repellent plants",
        views:2850,
        likes:58,
        dislikes:2,
        channel: "Backyard Gardening",
        postedOn: "May 10, 2018",
        subscriber: "115K",
        duration: "1:41",
        description:"please check top 5 mosquito repellent plants"
      },
      {
        v_id: "I8fywZ6l5Xk",
        category: "Growing Fruits",
        avatar: "http://i3.ytimg.com/vi/hytZVgkX-7Q/maxresdefault.jpg",
        title:"How to grow Papaya :- Complete Guide with Tips!!",
        views:1206,
        likes:29,
        dislikes:0,
        channel: "Backyard Gardening",
        postedOn: "Sep 17, 2017",
        subscriber: "115K",
        duration: "3:56",
        description:"Please go through the complete guide on how to grow papaya with helpful tips and tricks."
      },
      {
        v_id: "hGiQk6e9z7Q",
        category: "Growing Fruits",
        avatar: "http://i3.ytimg.com/vi/MHFvC5Rm5Pw/maxresdefault.jpg",
        title:"Grow Pineapple plant from Pineapple crown",
        views:2018,
        likes:33,
        dislikes:3,
        channel: "Backyard Gardening",
        postedOn: "Jul 17, 2017",
        subscriber: "115K",
        duration: "2:58",
        description:"Learn the easiest way to grow your own pineapples in pot/containers/garden."
      },
      {
        v_id: "bTPUwgaxASI",
        category: "Growing Fruits",
        avatar: "http://i3.ytimg.com/vi/Nc_gHJBDfxk/maxresdefault.jpg",
        title:"Grow Tomatoes from Tomato : Step by Step Complete Guide",
        views:3468,
        likes:87,
        dislikes:3,
        channel: "Backyard Gardening",
        postedOn: "Apr 29, 2107",
        subscriber: "115K",
        duration: "5:27",
        description:"In this video we will show the complete process to grow tomatoes from a tomato (no need to buy seeds). Right from getting seeds from a tomato, soil preparation, sowing seed and finally harvesting the tomatoes. "
      },
      {
        v_id: "zM6BJ8You5E",
        category: "Growing Fruits",
        avatar: "http://i3.ytimg.com/vi/RtVRqp9nKwI/maxresdefault.jpg",
        title:"Grow Sugarcane in your garden with easy tips||How to grow Sugarcane||Backyard Gardening",
        views:2413,
        likes:26,
        dislikes:5,
        channel: "Backyard Gardening",
        postedOn: "Jan 12, 2019",
        subscriber: "115K",
        duration: "2:52",
        description:"Easy way of growing sugarcane in the garden backyard"
      }]